version: 2.1

orbs:
  # heroku: circleci/heroku@x.y
  node: circleci/node@3.0.0

jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint

workflows:
  eslint:
    jobs:
      - lint
  node-tests:
    jobs:
      - node/test
  # deploy:
  #   jobs:
  #     - heroku/deploy-via-git:
  #       filters:
  #         branches:
  #           only:
  #             - master
  #       requires:
  #         - node/test

      