version: 2.1

orbs:
  # heroku: circleci/heroku@x.y
  node: circleci/node@3.0.0

jobs:
  lint:
    executor:
      name: node/default
    steps:
      - run:
          command: npm run lint
  build:
    docker:
      - image: circleci/postgres:latest
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nomi-ci
    executor:
      name: node/default
    steps:
      - checkout
       # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - node/install-packages
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  test-and-hold:
    jobs:
      - build
      - lint:
          requires:
            - build
      - node/test:
          requires:
            - build

  # deploy:
  #   jobs:
  #     - heroku/deploy-via-git:
  #       filters:
  #         branches:
  #           only:
  #             - master
  #       requires:
  #         - node/test

# jobs:
#   build:
#     docker:
#       - image: postgres:latest
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#         environment:
#           POSTGRES_USER: root