version: 2.1

orbs:
  # heroku: circleci/heroku@x.y
  node: circleci/node@4.2.0

jobs:
  lint:
    executor:
      name: node/default
    steps:
      - run:
          command: npm run lint
  build:
    executor:
      name: node/default
    docker:
      - image: circleci/node:latest
      - image: circleci/postgres:latest
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nomi-ci
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - node/install-packages
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

workflows:
  test-and-hold:
    jobs:
      - build
      - lint:
          requires:
            - build
      - node/test:
          requires:
            - lint

  # deploy:
  #   jobs:
  #     - heroku/deploy-via-git:
  #       filters:
  #         branches:
  #           only:
  #             - master
  #       requires:
  #         - node/test

# jobs:
#   build:
#     docker:
#       - image: postgres:latest
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#         environment:
#           POSTGRES_USER: root